name: notik
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  shared_preferences: ^2.0.15
  path: ^1.8.1
  flutter_slidable: ^1.3.0
  page_transition: ^2.0.9
  image_picker: ^0.8.5+3
  flutter_share: ^2.0.0
  hashtagable: ^2.1.0

  firebase_core: ^1.20.0
  firebase_database: ^9.0.20
  firebase_storage: ^10.3.4
  firebase_auth: ^3.5.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

